# Generated by Django 3.0.3 on 2022-04-07 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(help_text='folder name with path', max_length=70)),
                ('total_images', models.IntegerField(help_text='count total images in given folder')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(help_text='Save image name with path', max_length=100)),
                ('type', models.CharField(help_text='sended request to Api has sucess or error', max_length=15)),
                ('title', models.CharField(max_length=30)),
                ('score', models.FloatField(max_length=30)),
                ('label', models.CharField(max_length=30)),
                ('prediction_gender', models.CharField(max_length=30)),
                ('confidence_gender', models.CharField(max_length=30)),
                ('prediction_age', models.IntegerField(max_length=30)),
                ('confidence_age', models.IntegerField(max_length=30)),
                ('show_notification', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liveness.Task')),
            ],
            options={
                'db_table': 'result',
            },
        ),
    ]
