# Generated by Django 3.0.3 on 2022-04-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='confidence_age',
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='confidence_gender',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image_name',
            field=models.CharField(help_text='Save image name with path', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='label',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='prediction_age',
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='prediction_gender',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.FloatField(default=None, max_length=30, null=True),
        ),
    ]
