# Generated by Django 3.0.3 on 2022-04-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveness', '0003_auto_20220407_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='image_name',
            field=models.CharField(help_text='Save image name with path', max_length=100),
        ),
    ]
