# Generated by Django 3.0.3 on 2022-04-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveness', '0008_result_thumbnail_img_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='confidence_age',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='confidence_gender',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image_name',
            field=models.CharField(default=None, help_text='Save image name with path', max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='label',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='prediction_age',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='prediction_gender',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='result',
            name='title',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='result',
            name='type',
            field=models.CharField(default=None, help_text='sended request to Api has sucess or error', max_length=15),
        ),
    ]
