# Generated by Django 3.0.3 on 2022-04-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveness', '0010_auto_20220412_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='folder_type',
            field=models.BooleanField(default=True, help_text='If 1 Live 0 Spoof '),
        ),
    ]
